---
language: python
python: "2.7"
sudo: false
addons:
  apt:
    packages:
    - php5-cli
    - php5-curl
    - python-pip
cache:
  directories:
  - $HOME/virtualenv
  - $HOME/.composer
install:
  - pip install ansible --upgrade
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - ansible --version
  - ansible-galaxy install carlosbuenosvinos.ansistrano-deploy --force
  - ln -s `pwd` ../eheuje.ansistrano-symfony-deploy

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
