---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION: latest
    PHP_VERSION: 7.0
    SYMFONY_VERSION: 27
  - ANSIBLE_VERSION: latest
    PHP_VERSION: 7.2
    SYMFONY_VERSION: 34
  - ANSIBLE_VERSION: latest
    PHP_VERSION: 7.2
    SYMFONY_VERSION: 40

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update -qq
  - sudo apt-get -qq install php$PHP_VERSION-cli php$PHP_VERSION-xml
  - php$PHP_VERSION -v
  - php$PHP_VERSION -i

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
  - ansible --version
  - printf '[defaults]\nroles_path=../' > ansible.cfg
  - ln -s ./ansistrano-symfony-deploy ../cbrunnkvist.ansistrano-symfony-deploy
  - ansible-galaxy install carlosbuenosvinos.ansistrano-deploy --force

script:
  - ansible-playbook -i test/inventory test/symfony_$SYMFONY_VERSION.yml --syntax-check
  - ansible-playbook -i test/inventory test/symfony_$SYMFONY_VERSION.yml -vvvv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
